---
title: "R Notebook"
output: html_notebook
---


```{r}

library(tidyverse)
library(dplyr)
#library(waffle)
library(ggplot2)
library(extrafont)
library(showtext)
library(marquee)
library(glue)
library(scales)
library(ggtext)
library(ggforce)
library(patchwork)
library(sf)

censo_2022 <- readr::read_delim("C:/Users/Thais Pereira/Documents/relatorio_demografia_sp/dinamica_etaria_sp/censo_2022.csv", 
                                delim = ";", 
                                locale = locale(encoding = "latin1"))

subprefeituras <- readxl::read_excel("C:/Users/Thais Pereira/Documents/relatorio_demografia_sp/dinamica_etaria_sp/distritos.xlsx")

censo_2010 <- readxl::read_excel("C:/Users/Thais Pereira/Documents/relatorio_demografia_sp/dinamica_etaria_sp/censo_2010_1.xlsx")

setores_censo_2010 <- readxl::read_excel("C:/Users/Thais Pereira/Documents/relatorio_demografia_sp/dinamica_etaria_sp/censo_2010_2.xlsx")

censo_2000 <- readxl::read_excel("C:/Users/Thais Pereira/Documents/relatorio_demografia_sp/dinamica_etaria_sp/censo_2000_1.xlsx")

setores_censo_2000 <- readxl::read_excel("C:/Users/Thais Pereira/Documents/relatorio_demografia_sp/dinamica_etaria_sp/censo_2000_2.xlsx")

censos_anteriores <- readxl::read_excel("C:/Users/Thais Pereira/Documents/relatorio_demografia_sp/dinamica_etaria_sp/censos_anteriores.xlsx")


shp_distritos <- st_read("C:/Users/Thais Pereira/Documents/relatorio_demografia_sp/dinamica_etaria_sp/SIRGAS_SHP_subprefeitura/SIRGAS_SHP_subprefeitura.shp") %>%  as.data.frame() %>% 
  dplyr::mutate(sp_nome = stringr::str_to_title(sp_nome)) %>% 
  select(sp_nome, geometry) %>% 
  rename(Subprefeitura = sp_nome)


systemfonts::system_fonts()

font_add(
  family  = "Noto Sans",
  regular = "C:/Users/Thais Pereira/Documents/relatorio_demografia_sp/dinamica_etaria_sp/static/NotoSans-Regular.ttf",
  bold    = "C:/Users/Thais Pereira/Documents/relatorio_demografia_sp/dinamica_etaria_sp/static/NotoSans-Bold.ttf"
)

showtext_auto()


```


# Dado para o município

```{r}

# censo 2022

# Código mínimo para filtrar
codigos <- 355030801:355030896  # cria sequência de 801 a 896

censo_2022_1 <- censo_2022 %>%
  filter(CD_DIST %in% codigos) %>%
  rename(Distrito = NM_DIST) %>% 
  left_join(subprefeituras, by = "Distrito")

censo_2022_2 <- censo_2022_1 %>% 
  group_by(Subprefeitura) %>% 
  summarise(across(where(is.numeric), ~ sum(.x, na.rm = TRUE))) %>% 
  mutate(`0 a 14 anos` = `0 a 4 anos` + `5 a 9 anos` + `10 a 14 anos`, 
         `15 a 29 anos` = `15 a 19 anos` + `20 a 24 anos` + `25 a 29 anos`, 
         `30 a 59 anos` = `30 a 39 anos` + `40 a 49 anos`, 
         `60 +` = `60 a 69 anos` + `70 anos ou mais`) %>% 
  mutate(Ano = 2022) %>% 
  select(Ano, `Quantidade de moradores`, Subprefeitura, `0 a 14 anos`, `15 a 29 anos`, `30 a 59 anos`, `60 +`)
  

```



```{r}

# censo 2010


nomes_colunas <- list(
    'V001'= 'Pessoas residentes em domicílios particulares e domicílios coletivos',
    'V002'= 'Pessoas residentes em domicílios particulares permanentes',
    'V003'= 'Responsáveis pelos domicílios particulares',
    'V004'= 'Cônjuges ou companheiros(as) (de sexo diferente e do mesmo sexo da pessoa responsável) em domicílios particulares',
    'V005'= 'Filhos(as) do responsável e do cônjuge em domicílios particulares',
    'V006'= 'Filhos(as) somente do responsável em domicílios particulares',
    'V007'= 'Enteados(as) em domicílios particulares',
    'V008'= 'Genros ou noras em domicílios particulares',
    'V009'= 'Pais, mães, padrastos ou madrastas em domicílios particulares',
    'V010'= 'Sogros (as) em domicílios particulares',
    'V011'= 'Netos(as) em domicílios particulares',
    'V012'= 'Bisnetos(as) em domicílios particulares',
    'V013'= 'Irmãos ou irmãs em domicílios particulares',
    'V014'= 'Avôs ou avós em domicílios particulares',
    'V015'= 'Outros parentes em domicílios particulares',
    'V016'= 'Agregados(as) em domicílios particulares',
    'V017'= 'Conviventes em domicílios particulares',
    'V018'= 'Pensionistas em domicílios particulares',
    'V019'= 'Empregados(as) domésticos(as) em domicílios particulares',
    'V020'= 'Parentes de empregados(as) domésticos(as) em domicílios particulares',
    'V021'= 'Individuais em domicílio coletivo',
    'V022'= 'Pessoas com menos de 1 ano de idade',
    'V023'= 'Pessoas com menos de 1 mês de idade',
    'V024'= 'Pessoas com 1 mês de idade',
    'V025'= 'Pessoas com 2 meses de idade',
    'V026'= 'Pessoas com 3 meses de idade',
    'V027'= 'Pessoas com 4 meses de idade',
    'V028'= 'Pessoas com 5 meses de idade',
    'V029'= 'Pessoas com 6 meses de idade',
    'V030'= 'Pessoas com 7 meses de idade',
    'V031'= 'Pessoas com 8 meses de idade',
    'V032'= 'Pessoas com 9 meses de idade',
    'V033'= 'Pessoas com 10 meses de idade',
    'V034'= 'Pessoas com 11 meses de idade',
    'V035'= 'Pessoas de 1 ano de idade',
    'V036'= 'Pessoas com 2 anos de idade',
    'V037'= 'Pessoas com 3 anos de idade',
    'V038'= 'Pessoas com 4 anos de idade',
    'V039'= 'Pessoas com 5 anos de idade',
    'V040'= 'Pessoas com 6 anos de idade',
    'V041'= 'Pessoas com 7 anos de idade',
    'V042'= 'Pessoas com 8 anos de idade',
    'V043'= 'Pessoas com 9 anos de idade',
    'V044'= 'Pessoas com 10 anos de idade',
    'V045'= 'Pessoas com 11 anos de idade',
    'V046'= 'Pessoas com 12 anos de idade',
    'V047'= 'Pessoas com 13 anos de idade',
    'V048'= 'Pessoas com 14 anos de idade',
    'V049'= 'Pessoas com 15 anos de idade',
    'V050'= 'Pessoas com 16 anos de idade',
    'V051'= 'Pessoas com 17 anos de idade',
    'V052'= 'Pessoas com 18 anos de idade',
    'V053'= 'Pessoas com 19 anos de idade',
    'V054'= 'Pessoas com 20 anos de idade',
    'V055'= 'Pessoas com 21 anos de idade',
    'V056'= 'Pessoas com 22 anos de idade',
    'V057'= 'Pessoas com 23 anos de idade',
    'V058'= 'Pessoas com 24 anos de idade',
    'V059'= 'Pessoas com 25 anos de idade',
    'V060'= 'Pessoas com 26 anos de idade',
    'V061'= 'Pessoas com 27 anos de idade',
    'V062'= 'Pessoas com 28 anos de idade',
    'V063'= 'Pessoas com 29 anos de idade',
    'V064'= 'Pessoas com 30 anos de idade',
    'V065'= 'Pessoas com 31 anos de idade',
    'V066'= 'Pessoas com 32 anos de idade',
    'V067'= 'Pessoas com 33 anos de idade',
    'V068'= 'Pessoas com 34 anos de idade',
    'V069'= 'Pessoas com 35 anos de idade',
    'V070'= 'Pessoas com 36 anos de idade',
    'V071'= 'Pessoas com 37 anos de idade',
    'V072'= 'Pessoas com 38 anos de idade',
    'V073'= 'Pessoas com 39 anos de idade',
    'V074'= 'Pessoas com 40 anos de idade',
    'V075'= 'Pessoas com 41 anos de idade',
    'V076'= 'Pessoas com 42 anos de idade',
    'V077'= 'Pessoas com 43 anos de idade',
    'V078'= 'Pessoas com 44 anos de idade',
    'V079'= 'Pessoas com 45 anos de idade',
    'V080'= 'Pessoas com 46 anos de idade',
    'V081'= 'Pessoas com 47 anos de idade',
    'V082'= 'Pessoas com 48 anos de idade',
    'V083'= 'Pessoas com 49 anos de idade',
    'V084'= 'Pessoas com 50 anos de idade',
    'V085'= 'Pessoas com 51 anos de idade',
    'V086'= 'Pessoas com 52 anos de idade',
    'V087'= 'Pessoas com 53 anos de idade',
    'V088'= 'Pessoas com 54 anos de idade',
    'V089'= 'Pessoas com 55 anos de idade',
    'V090'= 'Pessoas com 56 anos de idade',
    'V091'= 'Pessoas com 57 anos de idade',
    'V092'= 'Pessoas com 58 anos de idade',
    'V093'= 'Pessoas com 59 anos de idade',
    'V094'= 'Pessoas com 60 anos de idade',
    'V095'= 'Pessoas com 61 anos de idade',
    'V096'= 'Pessoas com 62 anos de idade',
    'V097'= 'Pessoas com 63 anos de idade',
    'V098'= 'Pessoas com 64 anos de idade',
    'V099'= 'Pessoas com 65 anos de idade',
    'V100'= 'Pessoas com 66 anos de idade',
    'V101'= 'Pessoas com 67 anos de idade',
    'V102'= 'Pessoas com 68 anos de idade',
    'V103'= 'Pessoas com 69 anos de idade',
    'V104'= 'Pessoas com 70 anos de idade',
    'V105'= 'Pessoas com 71 anos de idade',
    'V106'= 'Pessoas com 72 anos de idade',
    'V107'= 'Pessoas com 73 anos de idade',
    'V108'= 'Pessoas com 74 anos de idade',
    'V109'= 'Pessoas com 75 anos de idade',
    'V110'= 'Pessoas com 76 anos de idade',
    'V111'= 'Pessoas com 77 anos de idade',
    'V112'= 'Pessoas com 78 anos de idade',
    'V113'= 'Pessoas com 79 anos de idade',
    'V114'= 'Pessoas com 80 anos de idade',
    'V115'= 'Pessoas com 81 anos de idade',
    'V116'= 'Pessoas com 82 anos de idade',
    'V117'= 'Pessoas com 83 anos de idade',
    'V118'= 'Pessoas com 84 anos de idade',
    'V119'= 'Pessoas com 85 anos de idade',
    'V120'= 'Pessoas com 86 anos de idade',
    'V121'= 'Pessoas com 87 anos de idade',
    'V122'= 'Pessoas com 88 anos de idade',
    'V123'= 'Pessoas com 89 anos de idade',
    'V124'= 'Pessoas com 90 anos de idade',
    'V125'= 'Pessoas com 91 anos de idade',
    'V126'= 'Pessoas com 92 anos de idade',
    'V127'= 'Pessoas com 93 anos de idade',
    'V128'= 'Pessoas com 94 anos de idade',
    'V129'= 'Pessoas com 95 anos de idade',
    'V130'= 'Pessoas com 96 anos de idade',
    'V131'= 'Pessoas com 97 anos de idade',
    'V132'= 'Pessoas com 98 anos de idade',
    'V133'= 'Pessoas com 99 anos de idade',
    'V134'= 'Pessoas com 100 anos ou mais de idade')

setores_censo_2010_1 <- 
  setores_censo_2010 %>% select(Cod_setor, Nome_do_distrito)
  

censo_2010_2 <- censo_2010 %>%
  rename(!!!setNames(names(nomes_colunas), nomes_colunas)) %>% 
  left_join(setores_censo_2010_1, by = "Cod_setor") %>% 
  mutate(Nome_do_distrito = tolower(Nome_do_distrito), 
         Nome_do_distrito = str_to_title(Nome_do_distrito, locale = "pt"),
         Nome_do_distrito = case_when(Nome_do_distrito  == "Alto De Pinheiros" ~ "Alto de Pinheiros", 
                                      Nome_do_distrito  == "Freguesia Do Ó" ~ "Freguesia do Ó", 
                                      Nome_do_distrito  == "Parque Do Carmo" ~ "Parque do Carmo", TRUE ~ Nome_do_distrito)) %>% 
  
  rename(Distrito = Nome_do_distrito) %>% 
  left_join(subprefeituras, by = "Distrito") %>% 
  mutate(across(
    starts_with("Pessoas"),
    ~ as.numeric(as.character(.))
  )) %>% 
  group_by(Subprefeitura) %>% 
  summarise(across(where(is.numeric), ~ sum(.x, na.rm = TRUE))) %>% 
  mutate(
    # 0 a 14 anos (inclui menos de 1 ano até 14 anos)
    `0 a 14 anos` = rowSums(across(c(
     `Pessoas com menos de 1 ano de idade`,
      `Pessoas com menos de 1 mês de idade`,
      `Pessoas com 1 mês de idade`,
      `Pessoas com 2 meses de idade`,
      `Pessoas com 3 meses de idade`,
      `Pessoas com 4 meses de idade`,
      `Pessoas com 5 meses de idade`,
      `Pessoas com 6 meses de idade`,
      `Pessoas com 7 meses de idade`,
      `Pessoas com 8 meses de idade`,
      `Pessoas com 9 meses de idade`,
      `Pessoas com 10 meses de idade`,
      `Pessoas com 11 meses de idade`,
      `Pessoas de 1 ano de idade`,
      `Pessoas com 2 anos de idade`,
      `Pessoas com 3 anos de idade`,
      `Pessoas com 4 anos de idade`,
      `Pessoas com 5 anos de idade`,
      `Pessoas com 6 anos de idade`,
      `Pessoas com 7 anos de idade`,
      `Pessoas com 8 anos de idade`,
      `Pessoas com 9 anos de idade`,
      `Pessoas com 10 anos de idade`,
      `Pessoas com 11 anos de idade`,
      `Pessoas com 12 anos de idade`,
      `Pessoas com 13 anos de idade`,
      `Pessoas com 14 anos de idade`
    ), as.numeric), na.rm = TRUE),
    
    # 15 a 29 anos
    `15 a 29 anos` = rowSums(across(c(
      `Pessoas com 15 anos de idade`,
      `Pessoas com 16 anos de idade`,
      `Pessoas com 17 anos de idade`,
      `Pessoas com 18 anos de idade`,
      `Pessoas com 19 anos de idade`,
      `Pessoas com 20 anos de idade`,
      `Pessoas com 21 anos de idade`,
      `Pessoas com 22 anos de idade`,
      `Pessoas com 23 anos de idade`,
      `Pessoas com 24 anos de idade`,
      `Pessoas com 25 anos de idade`,
      `Pessoas com 26 anos de idade`,
      `Pessoas com 27 anos de idade`,
      `Pessoas com 28 anos de idade`,
      `Pessoas com 29 anos de idade`
    ), as.numeric), na.rm = TRUE),
    
    # 30 a 59 anos
    `30 a 59 anos` = rowSums(across(c(
      `Pessoas com 30 anos de idade`,
      `Pessoas com 31 anos de idade`,
      `Pessoas com 32 anos de idade`,
      `Pessoas com 33 anos de idade`,
      `Pessoas com 34 anos de idade`,
      `Pessoas com 35 anos de idade`,
      `Pessoas com 36 anos de idade`,
      `Pessoas com 37 anos de idade`,
      `Pessoas com 38 anos de idade`,
      `Pessoas com 39 anos de idade`,
      `Pessoas com 40 anos de idade`,
      `Pessoas com 41 anos de idade`,
      `Pessoas com 42 anos de idade`,
      `Pessoas com 43 anos de idade`,
      `Pessoas com 44 anos de idade`,
      `Pessoas com 45 anos de idade`,
      `Pessoas com 46 anos de idade`,
      `Pessoas com 47 anos de idade`,
      `Pessoas com 48 anos de idade`,
      `Pessoas com 49 anos de idade`,
      `Pessoas com 50 anos de idade`,
      `Pessoas com 51 anos de idade`,
      `Pessoas com 52 anos de idade`,
      `Pessoas com 53 anos de idade`,
      `Pessoas com 54 anos de idade`,
      `Pessoas com 55 anos de idade`,
      `Pessoas com 56 anos de idade`,
      `Pessoas com 57 anos de idade`,
      `Pessoas com 58 anos de idade`,
      `Pessoas com 59 anos de idade`
    ), as.numeric), na.rm = TRUE),
    
    # 60 anos ou mais
    `60 +` = rowSums(across(c(
      `Pessoas com 60 anos de idade`,
      `Pessoas com 61 anos de idade`,
      `Pessoas com 62 anos de idade`,
      `Pessoas com 63 anos de idade`,
      `Pessoas com 64 anos de idade`,
      `Pessoas com 65 anos de idade`,
      `Pessoas com 66 anos de idade`,
      `Pessoas com 67 anos de idade`,
      `Pessoas com 68 anos de idade`,
      `Pessoas com 69 anos de idade`,
      `Pessoas com 70 anos de idade`,
      `Pessoas com 71 anos de idade`,
      `Pessoas com 72 anos de idade`,
      `Pessoas com 73 anos de idade`,
      `Pessoas com 74 anos de idade`,
      `Pessoas com 75 anos de idade`,
      `Pessoas com 76 anos de idade`,
      `Pessoas com 77 anos de idade`,
      `Pessoas com 78 anos de idade`,
      `Pessoas com 79 anos de idade`,
      `Pessoas com 80 anos de idade`,
      `Pessoas com 81 anos de idade`,
      `Pessoas com 82 anos de idade`,
      `Pessoas com 83 anos de idade`,
      `Pessoas com 84 anos de idade`,
      `Pessoas com 85 anos de idade`,
      `Pessoas com 86 anos de idade`,
      `Pessoas com 87 anos de idade`,
      `Pessoas com 88 anos de idade`,
      `Pessoas com 89 anos de idade`,
      `Pessoas com 90 anos de idade`,
      `Pessoas com 91 anos de idade`,
      `Pessoas com 92 anos de idade`,
      `Pessoas com 93 anos de idade`,
      `Pessoas com 94 anos de idade`,
      `Pessoas com 95 anos de idade`,
      `Pessoas com 96 anos de idade`,
      `Pessoas com 97 anos de idade`,
      `Pessoas com 98 anos de idade`,
      `Pessoas com 99 anos de idade`,
      `Pessoas com 100 anos ou mais de idade`
    ), as.numeric), na.rm = TRUE)
  ) %>% 
  mutate(Ano = 2010) %>% 
  select(Ano, Subprefeitura,  `Pessoas residentes em domicílios particulares e domicílios coletivos`, `0 a 14 anos`, `15 a 29 anos`, `30 a 59 anos`, `60 +`)

  


```



```{r}

# censo 2000

nomes_colunas_idade <- list(
  'V1347' = 'Pessoas com 0 anos de idade',
  'V1348' = 'Pessoas de 1 anos de idade',
  'V1349' = 'Pessoas com 2 anos de idade',
  'V1350' = 'Pessoas com 3 anos de idade',
  'V1351' = 'Pessoas com 4 anos de idade',
  'V1352' = 'Pessoas com 5 anos de idade',
  'V1353' = 'Pessoas com 6 anos de idade',
  'V1354' = 'Pessoas com 7 anos de idade',
  'V1355' = 'Pessoas com 8 anos de idade',
  'V1356' = 'Pessoas com 9 anos de idade',
  'V1357' = 'Pessoas com 10 anos de idade',
  'V1358' = 'Pessoas com 11 anos de idade',
  'V1359' = 'Pessoas com 12 anos de idade',
  'V1360' = 'Pessoas com 13 anos de idade',
  'V1361' = 'Pessoas com 14 anos de idade',
  'V1362' = 'Pessoas com 15 anos de idade',
  'V1363' = 'Pessoas com 16 anos de idade',
  'V1364' = 'Pessoas com 17 anos de idade',
  'V1365' = 'Pessoas com 18 anos de idade',
  'V1366' = 'Pessoas com 19 anos de idade',
  'V1367' = 'Pessoas com 20 anos de idade',
  'V1368' = 'Pessoas com 21 anos de idade',
  'V1369' = 'Pessoas com 22 anos de idade',
  'V1370' = 'Pessoas com 23 anos de idade',
  'V1371' = 'Pessoas com 24 anos de idade',
  'V1372' = 'Pessoas com 25 anos de idade',
  'V1373' = 'Pessoas com 26 anos de idade',
  'V1374' = 'Pessoas com 27 anos de idade',
  'V1375' = 'Pessoas com 28 anos de idade',
  'V1376' = 'Pessoas com 29 anos de idade',
  'V1377' = 'Pessoas com 30 anos de idade',
  'V1378' = 'Pessoas com 31 anos de idade',
  'V1379' = 'Pessoas com 32 anos de idade',
  'V1380' = 'Pessoas com 33 anos de idade',
  'V1381' = 'Pessoas com 34 anos de idade',
  'V1382' = 'Pessoas com 35 anos de idade',
  'V1383' = 'Pessoas com 36 anos de idade',
  'V1384' = 'Pessoas com 37 anos de idade',
  'V1385' = 'Pessoas com 38 anos de idade',
  'V1386' = 'Pessoas com 39 anos de idade',
  'V1387' = 'Pessoas com 40 anos de idade',
  'V1388' = 'Pessoas com 41 anos de idade',
  'V1389' = 'Pessoas com 42 anos de idade',
  'V1390' = 'Pessoas com 43 anos de idade',
  'V1391' = 'Pessoas com 44 anos de idade',
  'V1392' = 'Pessoas com 45 anos de idade',
  'V1393' = 'Pessoas com 46 anos de idade',
  'V1394' = 'Pessoas com 47 anos de idade',
  'V1395' = 'Pessoas com 48 anos de idade',
  'V1396' = 'Pessoas com 49 anos de idade',
  'V1397' = 'Pessoas com 50 anos de idade',
  'V1398' = 'Pessoas com 51 anos de idade',
  'V1399' = 'Pessoas com 52 anos de idade',
  'V1400' = 'Pessoas com 53 anos de idade',
  'V1401' = 'Pessoas com 54 anos de idade',
  'V1402' = 'Pessoas com 55 anos de idade',
  'V1403' = 'Pessoas com 56 anos de idade',
  'V1404' = 'Pessoas com 57 anos de idade',
  'V1405' = 'Pessoas com 58 anos de idade',
  'V1406' = 'Pessoas com 59 anos de idade',
  'V1407' = 'Pessoas com 60 anos de idade',
  'V1408' = 'Pessoas com 61 anos de idade',
  'V1409' = 'Pessoas com 62 anos de idade',
  'V1410' = 'Pessoas com 63 anos de idade',
  'V1411' = 'Pessoas com 64 anos de idade',
  'V1412' = 'Pessoas com 65 anos de idade',
  'V1413' = 'Pessoas com 66 anos de idade',
  'V1414' = 'Pessoas com 67 anos de idade',
  'V1415' = 'Pessoas com 68 anos de idade',
  'V1416' = 'Pessoas com 69 anos de idade',
  'V1417' = 'Pessoas com 70 anos de idade',
  'V1418' = 'Pessoas com 71 anos de idade',
  'V1419' = 'Pessoas com 72 anos de idade',
  'V1420' = 'Pessoas com 73 anos de idade',
  'V1421' = 'Pessoas com 74 anos de idade',
  'V1422' = 'Pessoas com 75 anos de idade',
  'V1423' = 'Pessoas com 76 anos de idade',
  'V1424' = 'Pessoas com 77 anos de idade',
  'V1425' = 'Pessoas com 78 anos de idade',
  'V1426' = 'Pessoas com 79 anos de idade',
  'V1427' = 'Pessoas com 80 anos de idade',
  'V1428' = 'Pessoas com 81 anos de idade',
  'V1429' = 'Pessoas com 82 anos de idade',
  'V1430' = 'Pessoas com 83 anos de idade',
  'V1431' = 'Pessoas com 84 anos de idade',
  'V1432' = 'Pessoas com 85 anos de idade',
  'V1433' = 'Pessoas com 86 anos de idade',
  'V1434' = 'Pessoas com 87 anos de idade',
  'V1435' = 'Pessoas com 88 anos de idade',
  'V1436' = 'Pessoas com 89 anos de idade',
  'V1437' = 'Pessoas com 90 anos de idade',
  'V1438' = 'Pessoas com 91 anos de idade',
  'V1439' = 'Pessoas com 92 anos de idade',
  'V1440' = 'Pessoas com 93 anos de idade',
  'V1441' = 'Pessoas com 94 anos de idade',
  'V1442' = 'Pessoas com 95 anos de idade',
  'V1443' = 'Pessoas com 96 anos de idade',
  'V1444' = 'Pessoas com 97 anos de idade',
  'V1445' = 'Pessoas com 98 anos de idade',
  'V1446' = 'Pessoas com 99 anos de idade',
  'V1447' = 'Pessoas com 100 ou mais anos de idade',
  'V1448' = 'Pessoas com 0 a 4 anos de idade',
  'V1449' = 'Pessoas com 5 a 9 anos de idade',
  'V1450' = 'Pessoas com 10 a 14 anos de idade',
  'V1451' = 'Pessoas com 15 a 19 anos de idade',
  'V1452' = 'Pessoas com 20 a 24 anos de idade',
  'V1453' = 'Pessoas com 25 a 29 anos de idade',
  'V1454' = 'Pessoas com 30 a 34 anos de idade',
  'V1455' = 'Pessoas com 35 a 39 anos de idade',
  'V1456' = 'Pessoas com 40 a 44 anos de idade',
  'V1457' = 'Pessoas com 45 a 49 anos de idade',
  'V1458' = 'Pessoas com 50 a 54 anos de idade',
  'V1459' = 'Pessoas com 55 a 59 anos de idade',
  'V1460' = 'Pessoas com 60 a 64 anos de idade',
  'V1461' = 'Pessoas com 65 a 69 anos de idade',
  'V1462' = 'Pessoas com 70 a 74 anos de idade',
  'V1463' = 'Pessoas com 75 a 79 anos de idade',
  'V1464' = 'Pessoas com 80 ou mais anos de idade'
)

setores_censo_2000_1 <- 
  setores_censo_2000 %>% 
  filter(Nome_do_municipio == "São Paulo") %>% 
  select(Cod_setor, Nome_do_distrito) %>% 
  mutate(Cod_setor = as.character(Cod_setor))


censo_2000_2 <- censo_2000 %>%
  rename(!!!setNames(names(nomes_colunas_idade), nomes_colunas_idade)) %>% 
  inner_join(setores_censo_2000_1, by = "Cod_setor") %>% 
  mutate(Nome_do_distrito = tolower(Nome_do_distrito), 
         Nome_do_distrito = str_to_title(Nome_do_distrito, locale = "pt"),
         Nome_do_distrito = case_when(Nome_do_distrito  == "Alto De Pinheiros" ~ "Alto de Pinheiros", 
                                      Nome_do_distrito  == "Freguesia Do Ó" ~ "Freguesia do Ó", 
                                      Nome_do_distrito  == "Parque Do Carmo" ~ "Parque do Carmo", TRUE ~ Nome_do_distrito)) %>% 
  rename(Distrito = Nome_do_distrito) %>% 
  select(starts_with(c("Pessoas", "Distrito"))) %>% 
  left_join(subprefeituras, by = "Distrito") %>% 
  group_by(Subprefeitura) %>% 
  summarise(across(where(is.numeric), ~ sum(.x, na.rm = TRUE))) %>% 
    mutate(
    # 0 a 14 anos (inclui menos de 1 ano até 14 anos)
    `0 a 14 anos` = rowSums(across(c(
      `Pessoas com 0 anos de idade`,
      `Pessoas de 1 anos de idade`,
      `Pessoas com 2 anos de idade`,
      `Pessoas com 3 anos de idade`,
      `Pessoas com 4 anos de idade`,
      `Pessoas com 5 anos de idade`,
      `Pessoas com 6 anos de idade`,
      `Pessoas com 7 anos de idade`,
      `Pessoas com 8 anos de idade`,
      `Pessoas com 9 anos de idade`,
      `Pessoas com 10 anos de idade`,
      `Pessoas com 11 anos de idade`,
      `Pessoas com 12 anos de idade`,
      `Pessoas com 13 anos de idade`,
      `Pessoas com 14 anos de idade`
    ), as.numeric), na.rm = TRUE),
    
    # 15 a 29 anos
    `15 a 29 anos` = rowSums(across(c(
      `Pessoas com 15 anos de idade`,
      `Pessoas com 16 anos de idade`,
      `Pessoas com 17 anos de idade`,
      `Pessoas com 18 anos de idade`,
      `Pessoas com 19 anos de idade`,
      `Pessoas com 20 anos de idade`,
      `Pessoas com 21 anos de idade`,
      `Pessoas com 22 anos de idade`,
      `Pessoas com 23 anos de idade`,
      `Pessoas com 24 anos de idade`,
      `Pessoas com 25 anos de idade`,
      `Pessoas com 26 anos de idade`,
      `Pessoas com 27 anos de idade`,
      `Pessoas com 28 anos de idade`,
      `Pessoas com 29 anos de idade`
    ), as.numeric), na.rm = TRUE),
    
    # 30 a 59 anos
    `30 a 59 anos` = rowSums(across(c(
      `Pessoas com 30 anos de idade`,
      `Pessoas com 31 anos de idade`,
      `Pessoas com 32 anos de idade`,
      `Pessoas com 33 anos de idade`,
      `Pessoas com 34 anos de idade`,
      `Pessoas com 35 anos de idade`,
      `Pessoas com 36 anos de idade`,
      `Pessoas com 37 anos de idade`,
      `Pessoas com 38 anos de idade`,
      `Pessoas com 39 anos de idade`,
      `Pessoas com 40 anos de idade`,
      `Pessoas com 41 anos de idade`,
      `Pessoas com 42 anos de idade`,
      `Pessoas com 43 anos de idade`,
      `Pessoas com 44 anos de idade`,
      `Pessoas com 45 anos de idade`,
      `Pessoas com 46 anos de idade`,
      `Pessoas com 47 anos de idade`,
      `Pessoas com 48 anos de idade`,
      `Pessoas com 49 anos de idade`,
      `Pessoas com 50 anos de idade`,
      `Pessoas com 51 anos de idade`,
      `Pessoas com 52 anos de idade`,
      `Pessoas com 53 anos de idade`,
      `Pessoas com 54 anos de idade`,
      `Pessoas com 55 anos de idade`,
      `Pessoas com 56 anos de idade`,
      `Pessoas com 57 anos de idade`,
      `Pessoas com 58 anos de idade`,
      `Pessoas com 59 anos de idade`
    ), as.numeric), na.rm = TRUE),
    
    # 60 anos ou mais
    `60 +` = rowSums(across(c(
      `Pessoas com 60 anos de idade`,
      `Pessoas com 61 anos de idade`,
      `Pessoas com 62 anos de idade`,
      `Pessoas com 63 anos de idade`,
      `Pessoas com 64 anos de idade`,
      `Pessoas com 65 anos de idade`,
      `Pessoas com 66 anos de idade`,
      `Pessoas com 67 anos de idade`,
      `Pessoas com 68 anos de idade`,
      `Pessoas com 69 anos de idade`,
      `Pessoas com 70 anos de idade`,
      `Pessoas com 71 anos de idade`,
      `Pessoas com 72 anos de idade`,
      `Pessoas com 73 anos de idade`,
      `Pessoas com 74 anos de idade`,
      `Pessoas com 75 anos de idade`,
      `Pessoas com 76 anos de idade`,
      `Pessoas com 77 anos de idade`,
      `Pessoas com 78 anos de idade`,
      `Pessoas com 79 anos de idade`,
      `Pessoas com 80 anos de idade`,
      `Pessoas com 81 anos de idade`,
      `Pessoas com 82 anos de idade`,
      `Pessoas com 83 anos de idade`,
      `Pessoas com 84 anos de idade`,
      `Pessoas com 85 anos de idade`,
      `Pessoas com 86 anos de idade`,
      `Pessoas com 87 anos de idade`,
      `Pessoas com 88 anos de idade`,
      `Pessoas com 89 anos de idade`,
      `Pessoas com 90 anos de idade`,
      `Pessoas com 91 anos de idade`,
      `Pessoas com 92 anos de idade`,
      `Pessoas com 93 anos de idade`,
      `Pessoas com 94 anos de idade`,
      `Pessoas com 95 anos de idade`,
      `Pessoas com 96 anos de idade`,
      `Pessoas com 97 anos de idade`,
      `Pessoas com 98 anos de idade`,
      `Pessoas com 99 anos de idade`,
      `Pessoas com 100 ou mais anos de idade`
    ), as.numeric), na.rm = TRUE)) %>% 
     mutate(Ano = 2000) %>% 
     select(Ano,Subprefeitura, `0 a 14 anos`, `15 a 29 anos`, `30 a 59 anos`, `60 +`) 
  



  

```


```{r}

# demais censos - 1991, 1980 e 1970


censos_anteriroes_1 <- censos_anteriores %>% 
  pivot_longer(
    cols = c(`1970`, `1980`, `1991`), 
    names_to = "Ano",                  
    values_to = "valor") %>% 
    mutate(Faixas = case_when(
    Faixas %in% c("0 a 4 anos", "5 a 9 anos", "10 a 14 anos") ~ "0 a 14 anos",
    Faixas %in% c("15 a 19 anos", "20 a 24 anos", "25 a 29 anos") ~ "15 a 29 anos",
    Faixas %in% c("30 a 34 anos", "35 a 39 anos", "40 a 44 anos", 
                  "45 a 49 anos", "50 a 54 anos", "55 a 59 anos") ~ "30 a 59 anos",
    Faixas %in% c("60 a 64 anos", "65 a 69 anos", "70 a 74 anos", 
                  "75 a 79 anos", "80 anos ou mais") ~ "60 +",
    TRUE ~ Faixas
  )) %>%
  group_by(Ano, Faixas) %>%
  summarise(Valor = sum(valor, na.rm = TRUE), .groups = "drop") %>% 
  group_by(Ano) %>% 
  mutate(
    Total_ano = sum(Valor, na.rm = TRUE),
    Percentual = round((Valor / Total_ano)*100)) %>%
  ungroup() %>%
  select(Ano, Faixas, Valor, Percentual) 



```



```{r}

# Preparando os dados para o gráfico


dados_2022 <- censo_2022_2 %>% 
    mutate(Ano = as.character(Ano)) %>% 
    group_by(Ano) %>% 
    summarise(across(where(is.numeric), ~ sum(.x, na.rm = TRUE))) %>% 
    pivot_longer(
    cols = c(`0 a 14 anos`, `15 a 29 anos`, `30 a 59 anos`, `60 +`), 
    names_to = "Faixas",                  
    values_to = "Valor") %>% 
    mutate(
    Percentual = round((Valor / `Quantidade de moradores`)*100)) %>%
    ungroup() %>% 
    select(Ano, Faixas, Valor, Percentual) 

  


dados_2010 <- censo_2010_2 %>% 
  mutate(Ano = as.character(Ano)) %>% 
    group_by(Ano) %>% 
    summarise(across(where(is.numeric), ~ sum(.x, na.rm = TRUE))) %>% 
    pivot_longer(
    cols = c(`0 a 14 anos`, `15 a 29 anos`, `30 a 59 anos`, `60 +`), 
    names_to = "Faixas",                  
    values_to = "Valor") %>% 
    mutate(
    Percentual = round((Valor / `Pessoas residentes em domicílios particulares e domicílios coletivos`)*100)) %>%
    ungroup() %>% 
    select(Ano, Faixas, Valor, Percentual)



dados_2000 <- censo_2000_2 %>% mutate(Ano = as.character(Ano)) %>% 
    group_by(Ano) %>% 
    summarise(across(where(is.numeric), ~ sum(.x, na.rm = TRUE))) %>% 
    pivot_longer(
    cols = c(`0 a 14 anos`, `15 a 29 anos`, `30 a 59 anos`, `60 +`), 
    names_to = "Faixas",                  
    values_to = "Valor") %>% 
    mutate(
    Total_ano = sum(Valor, na.rm = TRUE),
    Percentual = round((Valor / Total_ano)*100)) %>%
    ungroup()%>% 
    select(Ano, Faixas, Valor, Percentual)


base_completa <- bind_rows(dados_2022, dados_2010, dados_2000, censos_anteriroes_1)

```



```{r}

cores <- c("0 a 14 anos" = "#53519b", "15 a 29 anos" = "#70a3c0", "30 a 59 anos" = "#C0AED9", "60 +" = "#834A6C")


# tema

subtitulo <- glue(
  "No gráfico vemos a evolução das faixas etárias de <b style='color:#53519b;'>0 a 14 anos</b>, <b style='color:#70a3c0;'>15 a 29 anos</b>, <b style='color:#C0AED9;'>30 a 59 anos</b> e  <b style='color:#834A6C;'>60+</b><br>ao longo dos últimos 6 censos"
)

# Grafico

waffle <- base_completa %>% 
  ggplot(aes(fill = Faixas, values = Percentual)) + 
  geom_waffle(color = "white", size = .25, n_rows = 8, flip = TRUE) +
  facet_wrap(~Ano, nrow = 1, strip.position = "bottom") +
  scale_y_continuous(labels = function(x) paste0(x * 10, "%"), expand = c(0.1,0.1)) +
  scale_x_discrete() + 
  coord_equal()+
  theme_void(base_family = "Noto Sans")+
  scale_colour_manual(values = cores, aesthetics = c("colour", "fill")) +
  labs(title = "A dinâmica etária em São Paulo ao longo dos Censos",
      subtitle = subtitulo,
      caption = "Fonte: IBGE") +
      theme(
          strip.text = element_text(size = 45, color = "#404044"),
          plot.background = element_rect(fill = "#F7F7F7", colour = "#F7F7F7"),
          panel.background = element_rect(fill = "#F7F7F7", colour = NA),
          plot.title = element_text(size = 70, face = "bold", hjust = 0, vjust = 7, color ="#53519b"),
          plot.subtitle = element_markdown(hjust = 0, vjust = 20, size = 40, lineheight = 0.4, color ="#404044",
                                           margin = margin(t = -8, b = 15)),
          plot.caption = element_text(hjust = 0.99, size = 30, lineheight = 1, vjust = -10, color = "darkgray"),
          axis.text.y = element_blank(),
          legend.position = "none",
          plot.margin = margin(1, 1, 1, 1, "cm"),
          panel.spacing = unit(0.2, "cm"),
          legend.title = element_blank())

ggsave("waffle.png", 
       plot = waffle,
       width = 8, 
       height = 4,
       dpi = 400)


```



```{r}


# Linha do tempo 

base_completa_1 <- base_completa %>%
  mutate(cor_dest = ifelse(Faixas == "60 +", "dest", "outras"))

labels_finais <- base_completa_1 %>%
  group_by(Faixas) %>%
  filter(Ano == max(Ano)) %>% 
  mutate(Faixas = case_when(Faixas == "0 a 14 anos" ~ "0 a 14",
                            Faixas == "15 a 29 anos" ~ "15 a 29",
                            Faixas == "30 a 59 anos" ~ "30 a 59", TRUE ~ Faixas)) 
  
  
grafico_linha <- ggplot(base_completa_1, aes(x = Ano, y = Percentual,  group = Faixas, color = cor_dest)) +
  geom_line(linewidth = 1) +
  geom_point(size = 5, alpha = 0.7) +
  theme_minimal(base_family = "Noto Sans") +
  scale_y_continuous(
  labels = function(x) paste0(x, "%")
  ) +
  geom_text(data = labels_finais %>% filter(Faixas != "60 +"),
            aes(label = Faixas),
            hjust = -0.3,
            size = 16,
            fontface = "bold",
            show.legend = FALSE) +
  geom_text(
  data = labels_finais %>% filter(Faixas == "60 +"),
  aes(label = Faixas),
  hjust = -0.2,
  vjust = 2.5,   
  size = 17,
  fontface = "bold",
  color = "#834A6C",   
  show.legend = FALSE
) +
  scale_color_manual(values = c(
    "outras" = "#d4d4d4",   # cinza claro
    "dest"   = "#834A6C"    # azul destaque
  )) +
  scale_x_discrete(expand = expansion(mult = c(0.06, 0.15))) +
  labs(title = "O Crescimento da População Idosa nos Últimos Censos",
      subtitle = "A população idosa foi de apenas 2% na década de 70 para quase 20% no último censo,\num aumento de cerca de 300% em 50 anos",
      x = "", 
      y = "",
      caption = "Fonte: IBGE") +
      theme(
          axis.text.x = element_text(size = 40, color = "#404044"),
          axis.text.y = element_text(size = 40, color = "#404044"),
          plot.background = element_rect(fill = "#F7F7F7", colour = "#F7F7F7"),
          panel.background = element_rect(fill = "#F7F7F7", colour = NA),
          plot.title = element_text(size = 70, face = "bold", hjust = 0, vjust = 4, color ="#53519b"),
          plot.subtitle = element_text(size = 40, hjust = 0, vjust = 4, lineheight = 0.3, color = "#404044"),
          plot.caption = element_text(hjust = 0.99, size = 30, vjust = -10, color = "darkgray"),
          legend.position = "none",
          plot.margin = margin(1, 1, 1, 1, "cm"),
          panel.spacing = unit(0.2, "cm"),
          legend.title = element_blank())

ggsave("grafico_linha.png", 
       plot = grafico_linha,
       width = 8, 
       height = 5,
       dpi = 400)

```



```{r}


recod <- c(
  "Aricanduva-Formosa-Carrao" = "Aricanduva-Formosa\nCarrao",
  "Vila Maria-Vila Guilherme" = "Vila Maria\nVila Guilherme",
  "Casa Verde-Cachoeirinha" = "Casa Verde\nCachoeirinha",
  "Freguesia-Brasilandia" = "Freguesia\nBrasilandia"
)
  
meu_labeller <- as_labeller(function(x) {
  # Se o nome está na lista, substitui; senão, mantém
  ifelse(x %in% names(recod), recod[x], x)
})

# Dado por Subprefeitura

cores <- c("0 a 14" = "#53519b", "15 a 29" = "#70a3c0", "30 a 59" = "#C0AED9", "60 + " = "#834A6C")


legenda_df <- tibble(
  Faixas = factor(
    names(cores),
    levels = c("60 + ", "30 a 59", "15 a 29", "0 a 14"), ordered = TRUE
  ),
  Valor = 1
)


grafico_legenda <- ggplot(legenda_df, aes(x = 1, y = Valor, fill = Faixas)) +
  geom_bar(stat = "identity", width = 0.3, position = "fill") +
  scale_fill_manual(values = cores, breaks = levels(legenda_df$Faixas)) +
  geom_text(aes(label = Faixas), 
            position = position_fill(vjust = 0.5),
            color = "white",
            size = 16,
            fontface = "bold") +
  coord_flip() +
  theme_void() +
  theme(
    plot.margin = margin(150, 20, 150, 20),
    theme(plot.background = element_rect(color = "#F7F7F7", fill = NA)), 
    legend.position = "none"
  )

barras <- censo_2022_2 %>% 
  mutate(`0 a 14` = `0 a 14 anos`/`Quantidade de moradores`, 
         `15 a 29` = `15 a 29 anos`/`Quantidade de moradores`, 
         `30 a 59` = `30 a 59 anos`/`Quantidade de moradores`, 
         `60 + ` = `60 +`/`Quantidade de moradores`) %>% 
  pivot_longer(
  cols = c(`0 a 14`, `15 a 29`, `30 a 59`, `60 + `), 
  names_to = "Faixas",                  
  values_to = "Valor") %>% 
  ggplot(aes(x = Faixas, y = Valor, fill = Faixas)) +
  geom_col() +
  facet_wrap(
  ~ Subprefeitura,
  labeller = meu_labeller
)+ 
  scale_y_continuous(
  labels = function(x) paste0(x, "%")) +
  theme_void(base_family = "Noto Sans")+
  geom_text(aes(x = Faixas, y = Valor, 
                label = scales::percent(Valor, accuracy = 1)),
            size = 16, fontface = "bold", vjust = 2, color = "#F7F7F7", family = "Noto Sans") +
  scale_colour_manual(values = cores, aesthetics = c("colour", "fill")) +
    labs(title = "A Distribuição das Faixas Etárias nas Subprefeituras (Censo 2022)",
      subtitle = "",
      x = "", 
      y = "",
      caption = "Fonte: IBGE") +
      theme(
          strip.text = element_text(size = 48, face = "bold", color = "#404044", lineheight  = 0.3,
                                    margin = margin(t = 0, r = 0, b = 0, l = 0)), 
          strip.background = element_rect(linewidth = 0, color = "#F7F7F7"),
          axis.text.x = element_blank(),
          axis.text.y = element_blank(),
          plot.background = element_rect(fill = "#F7F7F7", colour = "#F7F7F7"),
          panel.background = element_rect(fill = "#F7F7F7", colour = NA),
          plot.title = element_text(size = 100, face = "bold", hjust = 0, vjust = 10, color ="#53519b"),
          plot.subtitle = element_text(size = 40, hjust = 0, vjust = 4, lineheight = 0.3, color = "#404044"),
          plot.caption = element_text(hjust = 0.99, size = 50, vjust = -7, color = "darkgray"),
          legend.position = "none",
          plot.margin = margin(3, 1, 1, 1, "cm"),
          panel.spacing = unit(0.5, "cm"),
          legend.title = element_blank())

combinado <- barras +
  inset_element(
    grafico_legenda,
    left = 0.30,     # puxa para esquerda
    right = 0.70,    # puxa para direita — fica centralizado
    bottom = 0.89,   # sobe a caixa
    top = 1.28 # chega mais perto do título
  )
ggsave("grafico_barras.png", 
       plot = combinado,
       width = 15, 
       height = 15,
       dpi = 300)

  

```




```{r}


dados_mapas <- bind_rows(censo_2022_2, censo_2010_2, censo_2000_2) %>% 
  select(Ano, Subprefeitura, `60 +`) %>% 
  left_join(shp_distritos, by = "Subprefeitura") %>% 
  st_as_sf()


labels_k <- function(x) {
  paste0(x / 1000, "k")
}

# -----------------

mapas <-  dados_mapas %>% 
    ggplot() +
    geom_sf(aes(fill = `60 +`), color = "#F4E8F0", size = 0.2) +
    scale_fill_gradientn(
    colours = c("#F4E8F0", "#D1A9C3", "#A06A8B", "#834A6C"),
    name = "Idosos (60+)",
    labels = labels_k) +
    facet_wrap(~ Ano) +
    labs(title = paste("")) +
    theme_void(base_family = "Noto Sans")+
    labs(title = "Quantidade de Idosos ao longos dos últimos censos",
      subtitle = "",
      x = "", 
      y = "",
      caption = "Fonte: IBGE") +
      theme(
          strip.text = element_text(size = 40, color = "#404044",
                                    margin = margin(t = 0, r = 0, b = 0, l = 0)), 
          axis.text.x = element_blank(),
          axis.text.y = element_blank(),
          plot.background = element_rect(fill = "#F7F7F7", colour = "#F7F7F7"),
          panel.background = element_rect(fill = "#F7F7F7", colour = NA),
          plot.title = element_text(size = 50, face = "bold", hjust = 0, vjust = 5, color ="#53519b"),
          plot.caption = element_text(hjust = 2, size = 35, vjust = -7, color = "darkgray"),
          legend.position = "top",
          legend.text = element_text(size = 25, color = "#404044"),
          legend.key.width = unit(1, "cm"),legend.key.height = unit(0.4, "cm"),
          legend.box.margin = margin(t = 8, r = 0, b = 10, l = 0),
          plot.margin = margin(1, 0.2, 0.2, 0.2, "cm"),
          panel.spacing = unit(0.5, "cm"),
          legend.title = element_blank())
  
  ggsave("mapas.png", 
       plot = mapas,
       width = 8, 
       height = 5,
       dpi = 300)

  
  
  
```


```{r}

censo_2000_2 %>% 
  select(Subprefeitura, idosos_2000 = `60 +`) %>% 
  inner_join(
    censo_2022_2 %>% 
      select(Subprefeitura, idosos_2022 = `60 +`),
    by = "Subprefeitura"
  ) %>% 
  mutate(
    ganho = idosos_2022 - idosos_2000,
    crescimento_perc = (idosos_2022 - idosos_2000) / idosos_2000 * 100
  ) %>% 
  arrange(crescimento_perc)


```


```{r}

library(tidyverse)
library(sf)
library(roughsf)
library(geobr)


ger <- dados_mapas %>% 
  filter(Ano == 2022) %>% 
  st_set_crs(4674) %>% 
  st_transform(3857) %>%         # 2️⃣ projeção plana
  st_simplify(dTolerance = 50) %>%
  st_cast("POLYGON")

ger <- st_cast(dados_mapas, "POLYGON")
ger$fill <- c('#70a3c0')
ger$stroke <- 0.5
ger$fillweight <- 0.5


map_br_sketchy <- roughsf::roughsf(ger,
    title = "Sketchy Map of São Paulo", caption = "",
    title_font = "20px Pristina", font = "20px Pristina", caption_font = "15px Pristina",
    roughness = 0.5, bowing = 0.5, simplification = 0.5,
    width = 300, height = 450,
     
    )

# roughsf::save_roughsf(wait = 900,
#   rsf = map_br_sketchy,
#   file = "map_br_sketchy.png",
#   background = "#F7F7F7"
# )

map_br_sketchy

```




# teste

```{r}

dados_mapas <- bind_rows(censo_2022_2, censo_2010_2, censo_2000_2) %>% 
  select(Ano, Subprefeitura, `60 +`) %>% 
  left_join(shp_distritos, by = "Subprefeitura") %>% 
  st_as_sf()


labels_k <- function(x) {
  paste0(x / 1000, "k")
}

# ------------------ tooltip


dados_mapas <- dados_mapas %>% 
  mutate(
    tooltip = paste0(
      "<b>", Subprefeitura, "</b><br>",
      "Ano: ", Ano, "<br>",
      "Idosos (60+): ", scales::comma(`60 +`)
    )
  )


# -----------------

library(ggiraph)

mapa_interativo <- ggplot(dados_mapas) +
  geom_sf_interactive(
    aes(
      fill = `60 +`,
      tooltip = tooltip,
      data_id = Subprefeitura
    ),
    color = "#F4E8F0",
    size = 0.2
  ) +
  scale_fill_gradientn(
    colours = c("#F4E8F0", "#D1A9C3", "#A06A8B", "#834A6C"),
    name = "",
    labels = labels_k
  ) +
  facet_wrap(~ Ano) +
  theme_void(base_family = "Noto Sans") +
  labs(
    title = "Quantidade de Idosos ao longo dos últimos censos",
    caption = "Fonte: IBGE"
  ) +
  theme(
    strip.text = element_text(size = 20, color = "#404044"),
    plot.background = element_rect(fill = "white", colour = "white"),
    panel.background = element_rect(fill = "white", colour = NA),
    plot.title = element_text(size = 20, face = "bold", hjust = 0, vjust = 2, color ="#53519b"),
    plot.caption = element_text(hjust = 1, size = 15, color = "darkgray"),
    legend.position = "top",
    legend.text = element_text(size = 12, color = "#404044"),
    legend.key.width = unit(1, "cm"),
    legend.key.height = unit(0.4, "cm"),
    legend.box.margin = margin(t = 10, b = 12),
    panel.spacing = unit(1.5, "cm"),
    plot.margin = margin(0.5, 1,1, 1, "cm")
  )
  
mapa_girafe <- girafe(
  ggobj = mapa_interativo,
  width_svg = 8.9,
  height_svg = 5.9,
  options = list(
    opts_hover(css = "fill-opacity:0.9;"),
    opts_hover_inv(css = "fill-opacity:0.4;"),
    opts_selection(type = "none"),
    opts_sizing(rescale = TRUE),
    opts_toolbar(
    saveaspng = FALSE
)

    )
  )


# 🔹 aplica background no widget
mapa_girafe$x$style <- "
background-color: white;
"

mapa_girafe$x$style <- paste0(
  mapa_girafe$x$style,
  "
svg {
  background-color: white !important;
}
"
)

mapa_girafe


htmlwidgets::saveWidget(
  mapa_girafe,
  "mapa_idosos_interativo.html",
  selfcontained = TRUE,
  background = "white"
)

```








































